# Generated by Django 3.0 on 2020-02-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0002_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
