# Generated by Django 3.0 on 2020-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_auto_20200217_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='buyer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroommodel',
            name='seller',
            field=models.CharField(max_length=20),
        ),
    ]
