# Generated by Django 3.0 on 2020-02-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0005_auto_20200217_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
