# Generated by Django 3.0 on 2020-02-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0007_todomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textapp.Usermodel'),
        ),
    ]
