# Generated by Django 3.0 on 2020-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0008_auto_20200220_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='types',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
