# Generated by Django 3.0 on 2020-02-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0009_todomodel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroomlist', to='textapp.Textbookmodel'),
        ),
    ]
