# Generated by Django 3.0 on 2020-02-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0010_auto_20200223_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmodel',
            name='buyer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chatroommodel',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroomlist', to='textapp.Textbookmodel'),
        ),
    ]
