# Generated by Django 3.0 on 2020-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0011_auto_20200223_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmodel',
            name='campus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
