# Generated by Django 3.0 on 2020-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0012_textbookmodel_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmodel',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
