# Generated by Django 3.0 on 2020-02-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0013_textbookmodel_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='textapp.Textbookmodel'),
            preserve_default=False,
        ),
    ]
