# Generated by Django 3.0 on 2020-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0014_todomodel_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='dopk',
            field=models.IntegerField(default=0),
        ),
    ]
